import type { CardSeed, TarotCard } from "./types"

const cardImageNames = [
  "THE FOOL",
  "THE MAGICIAN",
  "THE HIGH PRIESTESS",
  "THE EMPRESS",
  "THE EMPEROR",
  "THE HIEROPHANT",
  "THE LOVERS",
  "THE CHARIOT",
  "STRENGTH",
  "THE HERMIT",
  "WHEEL of FORTUNE",
  "JUSTICE",
  "THE HANGED MAN",
  "DEATH",
  "TEMPERANCE",
  "THE DEVIL",
] as const

const toCardId = (name: string) => name.toLowerCase().replaceAll(" ", "-")

const cardSeeds: Partial<Record<(typeof cardImageNames)[number], CardSeed>> = {
  "THE FOOL": {
    number: 0,
    name: "The Fool",
    keywords: ["はじまり", "身軽さ", "未知", "飛び込む", "余白", "自由", "信頼", "小さな冒険"],
    symbolism: ["崖", "白い犬", "小さな荷物", "太陽", "白い花", "空", "一歩手前"],
    atmosphere: ["始まり", "自由", "未知", "軽やかさ", "無防備", "期待", "風通し"],
    observationAxes: [
      "まだ形になっていない可能性が、最初の一歩を求めています。",
      "身軽さは強みですが、足元を見ない楽観は小さな警告も含みます。",
      "余白を残したまま進むことで、今しか見えない道が開きます。",
      "準備不足に見えるものが、かえって自由な判断を助けることがあります。",
      "怖さと好奇心が同じ方向を向いているなら、その場所には意味があります。",
      "今日の失敗は、深刻な結末よりも地図を描くための印になりそうです。",
    ],
    reflectionPrompts: [
      "今日、完璧に準備できるまで待たなくてもよいことは何ですか。",
      "身軽になるために、いったん置いていける荷物は何ですか。",
      "自分が危険と呼んでいるものは、本当に危険ですか。",
      "小さく試すなら、どこまでなら笑って戻ってこられますか。",
      "未知に対して、警戒ではなく観察で近づける部分はどこですか。",
    ],
    answerNotes: [
      "このカードは、正解を知ってから動くより、動きながら輪郭を知る時によく出ます。",
      "怖さを消す必要はありません。怖さを持ったまま軽く試すことがテーマです。",
      "今は重い約束より、小さな実験の方が流れに合っています。",
      "見通しのなさは欠点ではなく、古い判断を外すための余白かもしれません。",
      "誰かに説明できる理由より、自分の中の微かな前向きさを拾うとよさそうです。",
      "ただし勢いだけで進むより、足元の小さなサインは確認しておくと安心です。",
    ],
    tensions: {
      expansive: ["自由", "冒険", "信頼", "軽さ"],
      restrictive: ["無防備", "見落とし", "足元の危うさ", "無計画"],
    },
    imagePrompt:
      "A quiet philosophical tarot card of The Fool at the edge of a cliff, small white dog, pale sun, minimal mystical atmosphere, deep violet night, contemplative mood",
  },
  "THE MAGICIAN": {
    number: 1,
    name: "The Magician",
    keywords: ["実行", "集中", "変換", "手元の道具", "意志", "創造", "媒介", "始動"],
    symbolism: ["机上の道具", "上を指す手", "下を指す手", "無限大", "赤い衣", "花", "作業台"],
    atmosphere: ["集中", "変換", "意志", "手触り", "鮮明さ", "準備完了", "技術"],
    observationAxes: [
      "材料はすでに手元にあり、必要なのはそれらを結び直す意志です。",
      "考えを現実へ移すには、まず小さな操作可能な形にする必要があります。",
      "力は誇示よりも、注意を向けた対象に静かに宿ります。",
      "今ある道具を数え直すと、足りないと思っていたものが別の姿で見つかります。",
      "言葉、時間、体力、人との接点のどれを使うかで結果の質が変わります。",
      "大きな変化より、最初の一手を正確に置くことが今日の中心です。",
    ],
    reflectionPrompts: [
      "今ある道具や経験のうち、まだ使っていないものは何ですか。",
      "今日、考えるだけでなく実際に手を動かせる一手は何ですか。",
      "自分が過小評価している技術や癖はありますか。",
      "願望を作業に変えるなら、最初の十五分で何をしますか。",
      "言葉で説明する前に、形にして見せられるものは何ですか。",
    ],
    answerNotes: [
      "このカードは、待つより作る方へ重心を移す合図です。",
      "手元の資源は不足しているというより、まだ配置されていないのかもしれません。",
      "完璧な計画より、動かせる試作品を作ると見えるものがあります。",
      "自信は先に必要ではなく、手を動かした後についてくる可能性があります。",
      "人を動かそうとする前に、自分の注意をどこへ置くかが問われています。",
      "うまくいかない時は、目的ではなく道具の選び方を変えると進みます。",
    ],
    tensions: {
      expansive: ["創造", "集中", "実行", "発明"],
      restrictive: ["操作", "過信", "言葉だけの意志", "器用貧乏"],
    },
    imagePrompt:
      "A restrained philosophical tarot card of The Magician, table with symbolic tools, one hand upward and one downward, violet-black ambience, subtle glow, contemplative composition",
  },
  "THE HIGH PRIESTESS": {
    number: 2,
    name: "The High Priestess",
    keywords: ["直感", "沈黙", "保留", "境界", "奥行き", "観察", "内側の声", "待つ"],
    symbolism: ["黒と白の柱", "巻物", "月冠", "ヴェール", "水", "影", "隠された知"],
    atmosphere: ["静けさ", "直感", "保留", "奥行き", "夜", "秘密", "冷静"],
    observationAxes: [
      "すぐに言葉にしないことで、見落としていた感覚が残ります。",
      "答えは外側の出来事より、出来事に対する微かな反応に隠れています。",
      "境界の向こうを急いで暴くより、境界があること自体を観察します。",
      "分からなさを敵にしない時、判断の精度が静かに上がります。",
      "今は表に出すことより、内側で熟すのを待つ時間かもしれません。",
      "違和感は小さくても、今日の重要な情報として扱う価値があります。",
    ],
    reflectionPrompts: [
      "まだ判断せずに置いておいた方がよいことは何ですか。",
      "説明できないけれど無視しない方がよい感覚はありますか。",
      "沈黙の中で、いちばん長く残る言葉は何ですか。",
      "誰かに見せる前に、自分だけで確かめたいことは何ですか。",
      "急いで答えを出すことで失われる情報はありますか。",
    ],
    answerNotes: [
      "このカードは、急いで結論を出さない勇気を示します。",
      "今の直感は、まだ理由を持っていなくても無視しない方がよさそうです。",
      "外へ説明するより、自分の中で静かに照合する時間が助けになります。",
      "秘密にすることと誠実でないことは別です。守るべき内側があります。",
      "見えていない部分を無理に明るくするより、暗さに目を慣らす段階です。",
      "答え合わせは、言葉より身体の反応に近いところで起きるかもしれません。",
    ],
    tensions: {
      expansive: ["直感", "受容", "沈黙", "洞察"],
      restrictive: ["閉ざしすぎ", "曖昧さ", "保留の長期化", "距離"],
    },
    imagePrompt:
      "A quiet philosophical tarot card of The High Priestess between black and white pillars, scroll, moon crown, veil, dark violet starlit ambience, subtle glow",
  },
  "THE EMPRESS": {
    number: 3,
    name: "The Empress",
    keywords: ["育てる", "実り", "受け取る", "身体感覚", "豊かさ", "手入れ", "安心", "余裕"],
    symbolism: ["豊かな庭", "小麦", "王冠", "クッション", "川", "果実", "柔らかい布"],
    atmosphere: ["育成", "実り", "身体感覚", "寛ぎ", "満ちる", "温度", "循環"],
    observationAxes: [
      "成果は押し出すだけでなく、育つ環境を整えることで現れます。",
      "身体の快不快は、理屈より早く状況の質を知らせます。",
      "与えることと受け取ることの均衡が、豊かさを長続きさせます。",
      "急がせるより、手入れを続ける方が強い変化につながります。",
      "今日の豊かさは、量ではなく満たされている感覚として現れます。",
      "誰かや何かを育てる前に、自分の土壌を整える必要があります。",
    ],
    reflectionPrompts: [
      "いま育てる価値がある関係や習慣は何ですか。",
      "自分の身体が求めている休息や手触りは何ですか。",
      "受け取ることを遠慮している場所はありますか。",
      "小さく手入れすれば回復しそうなものは何ですか。",
      "成果を急かさず、今日できる水やりは何ですか。",
    ],
    answerNotes: [
      "このカードは、がんばるより満ちることを思い出させます。",
      "今日の答えは、効率より心地よく続けられる形にありそうです。",
      "放置していたものに少し手をかけるだけで、流れが戻るかもしれません。",
      "与えすぎているなら受け取り、受け取りすぎているなら返す調整が鍵です。",
      "身体の声を軽く扱わないことが、判断の精度につながります。",
      "豊かさは派手な獲得ではなく、安心できる余白として現れそうです。",
    ],
    tensions: {
      expansive: ["豊かさ", "養育", "受容", "回復"],
      restrictive: ["過保護", "停滞", "依存", "甘やかし"],
    },
    imagePrompt:
      "A contemplative tarot card of The Empress in a lush moonlit garden, wheat, river, soft violet shadows, nurturing and grounded mood",
  },
  "THE EMPEROR": {
    number: 4,
    name: "The Emperor",
    keywords: ["境界", "責任", "構造", "決める", "安定", "守る", "秩序", "現実化"],
    symbolism: ["石の玉座", "山", "王笏", "鎧", "赤い衣", "四角い土台", "視線"],
    atmosphere: ["構造", "責任", "境界", "安定", "重み", "冷静", "統治"],
    observationAxes: [
      "気分に流されない枠組みが、動き続けるための足場になります。",
      "守るべき境界を明確にすると、余計な消耗が減ります。",
      "支配ではなく、責任を引き受ける姿勢が中心にあります。",
      "曖昧なままにした場所ほど、今日は言葉で線を引く必要があります。",
      "優しさを保つためにも、ルールや予定が助けになることがあります。",
      "自分の領域を整えると、他人の領域まで背負わなくてよくなります。",
    ],
    reflectionPrompts: [
      "今日、曖昧にせず決めた方がよい線引きは何ですか。",
      "自分が責任を持つ範囲と、持たなくてよい範囲はどこですか。",
      "安定のために、いま一つだけ固定するなら何ですか。",
      "誰かに許可を求めず、自分で決めてよいことは何ですか。",
      "強く出るのではなく、静かに守るべきものは何ですか。",
    ],
    answerNotes: [
      "このカードは、感情を消すことではなく、感情に足場を与えることを示します。",
      "今は柔らかく考えるより、先に枠を決めた方が楽になるかもしれません。",
      "責任を引き受けることと、全部を背負うことは違います。",
      "境界を示すことは冷たさではなく、関係を長持ちさせる技術です。",
      "今日の答えは、誰が何を決めるのかをはっきりさせる所にあります。",
      "もし窮屈に感じるなら、ルールを増やすより目的を確認するとよさそうです。",
    ],
    tensions: {
      expansive: ["安定", "決断", "保護", "責任"],
      restrictive: ["硬直", "支配", "孤立", "威圧"],
    },
    imagePrompt:
      "A solemn philosophical tarot card of The Emperor on a stone throne before mountains, red robe, armor, violet dusk, dignified and restrained",
  },
  "THE HIEROPHANT": {
    number: 5,
    name: "The Hierophant",
    keywords: ["学び", "型", "信頼", "継承", "教え", "共同体", "儀式", "意味づけ"],
    symbolism: ["二本の柱", "鍵", "祝福の手", "儀式", "弟子", "階段", "聖域"],
    atmosphere: ["伝統", "学び", "信頼", "型", "静かな規律", "相談", "共有"],
    observationAxes: [
      "型は自由を奪うものではなく、理解の入口になることがあります。",
      "誰から学ぶか、どの共同体に耳を傾けるかが方向を形作ります。",
      "信じている前提を見直すと、守りたい価値も見えてきます。",
      "独学で抱え込みすぎていることに、外の知恵を入れる余地があります。",
      "繰り返し行う小さな儀式が、心の置き場所を作ります。",
      "古いルールをそのまま従うのではなく、意味を問い直す時です。",
    ],
    reflectionPrompts: [
      "いま頼ってよい知恵や先例は何ですか。",
      "受け継いだ考えのうち、残したいものと手放したいものは何ですか。",
      "一人で判断せず、相談した方がよい相手はいますか。",
      "自分の中にある当たり前は、誰から受け取ったものですか。",
      "今日の行動に、静かな儀式として意味を持たせるなら何をしますか。",
    ],
    answerNotes: [
      "このカードは、独自性より先に土台となる型を確かめる時に出やすいです。",
      "答えは完全なオリジナルではなく、受け取った知恵の再解釈にありそうです。",
      "誰かに聞くことは弱さではなく、流れを早く正確にする方法です。",
      "守る価値のあるルールと、ただ古いだけのルールを分けて見るとよさそうです。",
      "今は大きな決断より、信頼できる手順に戻ることが助けになります。",
      "共同体に合わせるだけでなく、自分が何を信じるかを静かに選ぶ段階です。",
    ],
    tensions: {
      expansive: ["学習", "信頼", "継承", "相談"],
      restrictive: ["同調圧力", "形式主義", "思考停止", "権威依存"],
    },
    imagePrompt:
      "A quiet tarot card of The Hierophant in a dim sacred hall, keys and pillars, violet candlelight, contemplative traditional atmosphere",
  },
  "THE LOVERS": {
    number: 6,
    name: "The Lovers",
    keywords: ["選択", "結びつき", "誠実", "価値観", "対話", "調和", "本音", "一致"],
    symbolism: ["二人の人物", "天使", "木", "山", "選択", "裸の心", "光"],
    atmosphere: ["結びつき", "選択", "誠実さ", "調和", "親密さ", "迷い", "開示"],
    observationAxes: [
      "惹かれるものは、価値観を映す鏡として現れます。",
      "本当の選択は、何かを選び何かを選ばない責任を含みます。",
      "関係性の中で、自分の声を失わないことが調和を支えます。",
      "誰かに合わせる前に、自分が何に頷いているのかを確かめる時です。",
      "迷いは不誠実さではなく、価値観が複数あることのサインです。",
      "心地よい結びつきほど、正直な言葉を必要とします。",
    ],
    reflectionPrompts: [
      "今日の選択は、どんな価値観に忠実でありたいですか。",
      "誰かとの関係で、言葉にした方がよい本音はありますか。",
      "選ばないことで守れるものは何ですか。",
      "自分の欲求と相手への思いやりは、どこで重なりますか。",
      "調和のために黙っていることは、本当に調和を生んでいますか。",
    ],
    answerNotes: [
      "このカードは、外側の正解より自分の価値観との一致を問いかけます。",
      "今日の答え合わせは、好き嫌いではなく誠実でいられるかにあります。",
      "選ぶことは同時に何かを選ばないことです。その痛みも判断材料です。",
      "関係を壊さないための沈黙が、自分を薄めていないか確認するとよさそうです。",
      "本音を出すことで、むしろ結びつきが現実的になります。",
      "迷っているなら、誰にどう見られるかより、何を大切にしたいかへ戻る時です。",
    ],
    tensions: {
      expansive: ["調和", "愛", "一致", "誠実"],
      restrictive: ["迷い", "依存", "迎合", "先延ばし"],
    },
    imagePrompt:
      "A contemplative tarot card of The Lovers under a luminous angel, mountain and trees, deep violet twilight, intimate and symbolic mood",
  },
  "THE CHARIOT": {
    number: 7,
    name: "The Chariot",
    keywords: ["前進", "統御", "意志", "方向性", "突破", "集中", "勝利", "舵取り"],
    symbolism: ["戦車", "二頭のスフィンクス", "星の天蓋", "鎧", "都市", "車輪", "手綱のない制御"],
    atmosphere: ["前進", "統御", "意志", "緊張感", "速度", "集中", "挑戦"],
    observationAxes: [
      "対立する力を消すのではなく、同じ方向へ向けることが鍵です。",
      "勢いは役に立ちますが、進む理由が曖昧だと散らばります。",
      "勝利とは外側の制圧だけでなく、自分の衝動を扱う技術でもあります。",
      "止まる理由を探すより、進む方向を一つに絞ると力が戻ります。",
      "感情と理性のどちらかを捨てるのではなく、同じ車に乗せる時です。",
      "今日の突破口は、力の強さより舵取りの精度にあります。",
    ],
    reflectionPrompts: [
      "いま自分を別方向へ引いている二つの力は何ですか。",
      "進めるために、今日ひとつだけ決めるなら何を決めますか。",
      "勝ちたい気持ちの奥に、何を守りたい気持ちがありますか。",
      "勢いに任せず、方向を調整するための小さな確認は何ですか。",
      "自分の中の迷いを敵にせず、推進力に変えるならどう扱いますか。",
    ],
    answerNotes: [
      "このカードは、進む力はあるが方向を定める必要がある時に出やすいです。",
      "今日の答えは、気合いではなく優先順位を一つ決めることにありそうです。",
      "相反する気持ちがあるなら、片方を潰さず役割を与えると進みます。",
      "今は全員に理解されるより、自分が舵を握っている感覚が大切です。",
      "焦りが出ている時ほど、目的地の名前を短く言えるか確認してください。",
      "小さな勝利を取りに行くことで、大きな流れが動き始めます。",
    ],
    tensions: {
      expansive: ["前進", "統率", "達成", "突破"],
      restrictive: ["強引さ", "焦り", "分裂", "暴走"],
    },
    imagePrompt:
      "A focused tarot card of The Chariot with two sphinxes, starry canopy, violet night city behind, controlled motion and quiet intensity",
  },
  STRENGTH: {
    number: 8,
    name: "Strength",
    keywords: ["やわらかな強さ", "忍耐", "自制", "勇気", "受け止める", "統合", "優しさ", "内なる獣"],
    symbolism: ["獅子", "無限大", "白い衣", "花冠", "穏やかな手", "口元", "静かな視線"],
    atmosphere: ["柔らかい勇気", "自制", "忍耐", "信頼", "温かさ", "抑えない強さ", "和解"],
    observationAxes: [
      "強さは押し切る力ではなく、荒さを抱えたまま丁寧に扱う力です。",
      "感情を否定せず、反応するまでの間を作ることで選択肢が増えます。",
      "優しさは弱さではなく、長く保てる力の形です。",
      "今日扱うべきものは外の敵ではなく、自分の中の強い反応かもしれません。",
      "抑え込むより、名前をつけてそばに置く方が落ち着く感情があります。",
      "すぐに勝つことより、壊さずに向き合い続けることが力になります。",
    ],
    reflectionPrompts: [
      "今日、力で押すより穏やかに扱った方がよいものは何ですか。",
      "自分の中の荒い衝動に、どんな名前をつけられますか。",
      "優しくすることを、弱さと勘違いしている場所はありますか。",
      "反応する前に一呼吸置くなら、その間に何を確かめますか。",
      "長く保てる強さのために、今日ゆるめるべき緊張は何ですか。",
    ],
    answerNotes: [
      "このカードは、強く出るより丁寧に扱うことで本当の力が出る時に現れます。",
      "今日の答えは、感情を消すことではなく、感情と一緒に動ける形を探すことです。",
      "自分を責めるより、自分の反応を理解する方が次の選択につながります。",
      "優しさを選ぶことは、負けることではなく場を壊さない強さです。",
      "急いで結論を出さず、関係や状況が落ち着く時間を作るとよさそうです。",
      "内側の強い衝動は敵ではありません。扱い方を覚える相手です。",
    ],
    tensions: {
      expansive: ["勇気", "忍耐", "やわらかな統合", "信頼"],
      restrictive: ["抑圧", "我慢しすぎ", "内側の緊張", "消耗"],
    },
    imagePrompt:
      "A serene philosophical tarot card of Strength, gentle figure calming a lion, infinity symbol, flowers, deep violet dawn, quiet courage",
  },
}

const createMajorSeed = (
  number: number,
  name: string,
  keywords: string[],
  symbolism: string[],
): CardSeed => ({
  number,
  name,
  keywords,
  symbolism,
  atmosphere: ["静けさ", "転機", "内省", "象徴", "余白", "気づき"],
  observationAxes: [
    `${name}は、状況を急いで結論づける前に、今どこに力が集まっているかを見るカードです。`,
    "目立つ出来事よりも、繰り返し出ている感覚や小さな違和感に手がかりがあります。",
    "外側の正解ではなく、自分の中でまだ名前がついていない反応を観察すると読みやすくなります。",
  ],
  reflectionPrompts: [
    "今、見ないようにしている本音はありますか。",
    "今日ひとつだけ丁寧に扱うなら、何を選びますか。",
    "手放すことと守ることの境目は、どこにありますか。",
  ],
  answerNotes: [
    "このカードは、即断よりも観察を促しています。答えを固定する前に、状況の温度を確かめるとよさそうです。",
    "今の流れは、無理に押すよりも、意味のある一点へ注意を戻すことで整っていきます。",
    "不安そのものを消すより、不安が指している場所を静かに見つめることが助けになります。",
  ],
  tensions: {
    expansive: ["気づき", "解放", "成熟", "選択"],
    restrictive: ["停滞", "執着", "過剰反応", "見落とし"],
  },
  imagePrompt: `A contemplative philosophical tarot card of ${name}, deep violet atmosphere, quiet symbolic composition, subtle glow`,
})

const fallbackCardSeeds: Record<(typeof cardImageNames)[number], CardSeed> = {
  "THE FOOL": createMajorSeed(0, "The Fool", ["始まり", "自由", "未知"], ["崖", "白い犬", "小さな荷物"]),
  "THE MAGICIAN": createMajorSeed(1, "The Magician", ["実行", "集中", "創造"], ["机上の道具", "上を指す手", "無限大"]),
  "THE HIGH PRIESTESS": createMajorSeed(2, "The High Priestess", ["直感", "沈黙", "秘密"], ["柱", "巻物", "月"]),
  "THE EMPRESS": createMajorSeed(3, "The Empress", ["豊かさ", "育成", "受容"], ["庭", "麦", "王冠"]),
  "THE EMPEROR": createMajorSeed(4, "The Emperor", ["責任", "境界", "安定"], ["玉座", "山", "鎧"]),
  "THE HIEROPHANT": createMajorSeed(5, "The Hierophant", ["学び", "伝統", "信頼"], ["鍵", "柱", "祝福の手"]),
  "THE LOVERS": createMajorSeed(6, "The Lovers", ["選択", "調和", "誠実"], ["天使", "二人", "木"]),
  "THE CHARIOT": createMajorSeed(7, "The Chariot", ["前進", "統御", "勝利"], ["戦車", "スフィンクス", "星の天蓋"]),
  STRENGTH: createMajorSeed(8, "Strength", ["忍耐", "優しさ", "内なる力"], ["獅子", "無限大", "花冠"]),
  "THE HERMIT": createMajorSeed(9, "The Hermit", ["探求", "内省", "導き"], ["ランタン", "杖", "雪山"]),
  "WHEEL of FORTUNE": createMajorSeed(10, "Wheel of Fortune", ["転機", "循環", "流れ"], ["輪", "雲", "四つの象徴"]),
  JUSTICE: createMajorSeed(11, "Justice", ["均衡", "判断", "責任"], ["天秤", "剣", "柱"]),
  "THE HANGED MAN": createMajorSeed(12, "The Hanged Man", ["視点転換", "停止", "受容"], ["吊るされた人物", "光輪", "木"]),
  DEATH: createMajorSeed(13, "Death", ["終わり", "変容", "再生"], ["白い馬", "旗", "夜明け"]),
  TEMPERANCE: createMajorSeed(14, "Temperance", ["調整", "統合", "節度"], ["杯", "水の流れ", "翼"]),
  "THE DEVIL": createMajorSeed(15, "The Devil", ["執着", "欲望", "束縛"], ["鎖", "角", "暗い炎"]),
}

export const majorArcanaCards: TarotCard[] = cardImageNames.map((imageName) => ({
  id: toCardId(imageName),
  image: `/cards/${imageName}.png`,
  ...(cardSeeds[imageName] ?? fallbackCardSeeds[imageName]),
}))
